# Generated by Django 4.2.5 on 2023-10-31 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'Categoría de producto', 'verbose_name_plural': 'Categorías de productos'},
        ),
        migrations.AlterModelOptions(
            name='historicalcategoryproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Categoría de producto', 'verbose_name_plural': 'historical Categorías de productos'},
        ),
        migrations.AlterModelOptions(
            name='historicalindicator',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Indicador de oferta', 'verbose_name_plural': 'historical Indicadores de oferts'},
        ),
        migrations.AlterModelOptions(
            name='historicalmeasureunit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Unidad de medida', 'verbose_name_plural': 'historical Unidades de medidas'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Indicador de oferta', 'verbose_name_plural': 'Indicadores de oferts'},
        ),
        migrations.AlterModelOptions(
            name='measureunit',
            options={'verbose_name': 'Unidad de medida', 'verbose_name_plural': 'Unidades de medidas'},
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='category_product',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='measure_unit',
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='description',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='measure_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='historicalcategoryproduct',
            name='created_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='historicalcategoryproduct',
            name='deleted_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='historicalcategoryproduct',
            name='description',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historicalcategoryproduct',
            name='measure_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.measureunit', verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='historicalcategoryproduct',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='category_product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.categoryproduct', verbose_name='Categoría de producto'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='created_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='deleted_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='historicalmeasureunit',
            name='created_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='historicalmeasureunit',
            name='deleted_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='historicalmeasureunit',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='created_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='deleted_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Nombre de prducto'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='category_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='Categoría de producto'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre de prducto'),
        ),
    ]
